theme: jekyll-theme-cayman
title: "Amir Ranjbar"
description: "Bridging AI & Software - Scalable, Efficient Solutions"
baseurl: "" # Leave empty unless using a subpath
github_username: iamiranjbar
show_downloads: false
